# Generated by Django 5.0.6 on 2026-08-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_contacts', '0002_primary_secondary_contact_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencycontact',
            options={'ordering': ['contact_type', 'created_at']},
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
    ]
