from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
class Migration(migrations.Migration):
    initial=True
    dependencies=[('emergency_alerts','0002_response_fields'),('notifications','0001_initial'),('users','0001_initial')]
    operations=[
      migrations.CreateModel(name='NotificationDelivery',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('channel',models.CharField(choices=[('in_app','In App'),('push','Push'),('sms','SMS'),('email','Email')],max_length=20)),('status',models.CharField(choices=[('pending','Pending'),('sent','Sent'),('delivered','Delivered'),('failed','Failed')],default='pending',max_length=20)),('delivered_at',models.DateTimeField(blank=True,null=True)),('error_message',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('notification',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='deliveries',to='notifications.notification'))]),
      migrations.CreateModel(name='AlertResponse',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('role',models.CharField(max_length=30)),('status',models.CharField(choices=[('notified','Notified'),('accepted','Accepted'),('rejected','Rejected'),('on_way','On Way'),('arrived','Arrived'),('completed','Completed')],default='notified',max_length=20)),('response_time_seconds',models.PositiveIntegerField(blank=True,null=True)),('accepted_at',models.DateTimeField(blank=True,null=True)),('updated_at',models.DateTimeField(auto_now=True)),('created_at',models.DateTimeField(auto_now_add=True)),('alert',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='responses',to='emergency_alerts.emergencyalert')),('responder',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='alert_responses',to=settings.AUTH_USER_MODEL))]),
      migrations.CreateModel(name='ResponderAssignment',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('status',models.CharField(choices=[('assigned','Assigned'),('accepted','Accepted'),('on_way','On Way'),('arrived','Arrived'),('completed','Completed'),('cancelled','Cancelled')],default='assigned',max_length=20)),('assigned_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('alert',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='assignments',to='emergency_alerts.emergencyalert')),('assigned_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='assignments_made',to=settings.AUTH_USER_MODEL)),('responder',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='emergency_assignments',to=settings.AUTH_USER_MODEL))]),
      migrations.CreateModel(name='IncidentMessage',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('message',models.TextField()),('created_at',models.DateTimeField(auto_now_add=True)),('alert',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='messages',to='emergency_alerts.emergencyalert')),('sender',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='incident_messages',to=settings.AUTH_USER_MODEL))]),
      migrations.CreateModel(name='IncidentUpdate',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('status',models.CharField(max_length=30)),('note',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('actor',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='incident_updates',to=settings.AUTH_USER_MODEL)),('alert',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='incident_updates',to='emergency_alerts.emergencyalert'))]),
      migrations.AlterUniqueTogether(name='alertresponse',unique_together={('alert','responder')}),
      migrations.AlterUniqueTogether(name='responderassignment',unique_together={('alert','responder')}),
    ]
