# Generated by Django 5.0.6 on 2026-08-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_alerts', '0002_response_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyalert',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('active', 'Active'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
    ]
