let adminAlerts=[],adminMap=null,adminLayer=null,heatLayer=null;
const ACTIVE=['open','acknowledged','active','escalated'];

function role(){return String(CC.user?.role||'').toLowerCase()}
function isManager(){return ['admin','society_admin','superadmin','security_admin'].includes(role())}

function applyAdminRoleCopy(){
 const r=role();
 const copy={
   superadmin:['Platform Command Center','Global oversight for societies, configuration, audit visibility and emergency rules.'],
   admin:['Emergency Operations Center','Platform-wide emergency monitoring, escalation, responder performance and audit visibility.'],
   society_admin:['Society Emergency Command Center','Manage active incidents, residents, volunteers and security inside your assigned society.'],
   volunteer:['Volunteer Response Desk','Your assigned emergency queue. Accept, travel, arrive, assist and close the incident while keeping the resident informed.'],
   security_admin:['Security Admin Command Center','Manage security volunteers, view all society alerts, assign responders, analytics and audit visibility.'],
   security:['Security Response Desk','On-site emergency response for your society. Contact residents, coordinate responders and escalate critical incidents.']
 };
 const c=copy[r]||copy.admin;
 document.getElementById('adminRoleTitle')?.replaceChildren(document.createTextNode(c[0]));
 document.getElementById('adminRoleSummary')?.replaceChildren(document.createTextNode(c[1]));
 const panel=document.getElementById('responderDesk');
 if(panel&&['volunteer','security','security_volunteer'].includes(r)){panel.style.display='block';document.getElementById('responderDeskEyebrow').textContent=r==='security'?'SECURITY RESPONSE DESK':'VOLUNTEER RESPONSE DESK';document.getElementById('responderDeskTitle').textContent=r==='security'?'Immediate on-site response':'Your response tasks';document.getElementById('responderDeskSummary').textContent=r==='security'?'Accept security incidents, call the resident, share your position and escalate when required.':'Accept nearby emergencies, update your response state and communicate with the resident.';}
 const responderRole=['volunteer','security','security_volunteer'].includes(r);
 ['managerIntelligence','ownershipSection','mapSection','incidentManagementSection','managerStats'].forEach(id=>{const el=document.getElementById(id);if(el)el.style.display=responderRole?'none':''});
 const adminOnly=r==='security_admin'; if(adminOnly){['managerIntelligence','ownershipSection','mapSection','incidentManagementSection','managerStats'].forEach(id=>{const el=document.getElementById(id);if(el)el.style.display=''});}
 const management=document.getElementById('roleManagementPanel');
 if(management){
   const titles={security_admin:['Security administration','Manage security staff, assignments, society alerts, analytics and audit visibility'],society_admin:['Society responsibility','Residents · volunteers · security · active incidents · hotspots'],admin:['Platform responsibility','System incidents · responder performance · escalation rules · audit'],superadmin:['Global responsibility','Societies · system configuration · platform analytics · audit logs'],volunteer:['Responder responsibility','Emergency queue · response status · incident chat · location sharing'],security:['Security responsibility','On-site incidents · resident contact · escalation · response status']};
   const x=titles[r]||titles.admin;document.getElementById('roleManagementTitle').textContent=x[0];document.getElementById('roleManagementText').textContent=x[1];
   document.getElementById('roleManagementCards').innerHTML=(r==='society_admin'?['Residents','Active incidents','Volunteer readiness','Security on duty'].map((t,i)=>`<div class="role-management-card"><strong>${['👥','🚨','🤝','🛡️'][i]} ${t}</strong><span>Managed within your society</span></div>`):r==='admin'?['Platform incidents','Escalation','Responder load','Audit visibility'].map((t,i)=>`<div class="role-management-card"><strong>${['🚨','⚠️','📊','🧾'][i]} ${t}</strong><span>Platform-wide oversight</span></div>`):r==='superadmin'?['Societies','Configuration','Analytics','Audit logs'].map((t,i)=>`<div class="role-management-card"><strong>${['🏢','⚙️','📈','🧾'][i]} ${t}</strong><span>Global platform control</span></div>`):['Emergency queue','Resident contact','Response status','Incident chat'].map((t,i)=>`<div class="role-management-card"><strong>${['🚨','📞','📍','💬'][i]} ${t}</strong><span>Role-specific action</span></div>`)).join('');
 }
}

async function loadResponderDesk(){
 const list=document.getElementById('responderDeskList');if(!list||!['volunteer','security'].includes(role()))return;
 try{
  const d=await CC.json('/api/emergency-alerts/');const items=(Array.isArray(d)?d:(d.results||[])).filter(a=>ACTIVE.includes(String(a.status).toLowerCase()));
  list.innerHTML=items.length?items.slice(0,12).map(a=>{const phone=a.resident_phone||'';return `<div class="list-item responder-desk-row"><div class="row"><div><strong>🚨 #${a.id} · ${esc(a.alert_type)}</strong><div class="meta">${esc(a.resident_name||'Resident')} · ${fmt(a.created_at)} · ${esc(a.priority||'medium')}</div></div><span class="badge ${esc(a.status)}">${esc(a.status)}</span></div><p class="muted" style="margin-top:7px">${esc(a.message||'Emergency alert')}</p><div class="actions"><a class="btn btn-primary btn-sm" target="_blank" href="https://www.google.com/maps?q=${a.latitude},${a.longitude}">📍 Location</a>${phone?`<a class="btn btn-light btn-sm" href="tel:${esc(phone)}">📞 Call resident</a>`:''}<button class="btn btn-primary btn-sm" onclick="responderActionDesk(${a.id},'accepted')">Accept</button><button class="btn btn-light btn-sm" onclick="responderActionDesk(${a.id},'on_way')">On way</button><button class="btn btn-light btn-sm" onclick="responderActionDesk(${a.id},'arrived')">Arrived</button><button class="btn btn-success btn-sm" onclick="responderActionDesk(${a.id},'completed')">Resolve</button><a class="btn btn-light btn-sm" href="/emergency-history/?alert=${a.id}">💬 Chat</a>${['security','security_volunteer'].includes(role())?`<button class="btn btn-danger btn-sm" onclick="escalate(${a.id})">⚠ Escalate</button>`:''}</div></div>`}).join(''):'<div class="empty">No active emergencies require your response.</div>';
 }catch(e){list.innerHTML='<div class="empty">'+esc(e.message)+'</div>'}
}
async function responderActionDesk(id,action){try{await CC.json(`/api/response/alerts/${id}/respond/`,{method:'POST',body:JSON.stringify({action})});toast('Response updated: '+action,'success');loadResponderDesk();loadAdmin()}catch(e){toast(e.message,'error')}}

async function loadAdmin(){
 if(!isManager()){await loadResponderDesk();return}
 try{
  const [d,v,g]=await Promise.all([CC.json('/api/emergency-alerts/admin/'),CC.json('/api/volunteers/'),CC.json('/api/security/guards/')]);
  const vv=Array.isArray(v)?v:(v.results||[]),gg=Array.isArray(g)?g:(g.results||[]);document.getElementById('volunteers').textContent=vv.length;document.getElementById('availableVolunteers').textContent=vv.filter(x=>x.available_for_emergency).length;document.getElementById('guards').textContent=gg.length;document.getElementById('onDuty').textContent=gg.filter(x=>x.is_on_duty).length;
  adminAlerts=Array.isArray(d)?d:(d.results||[]);document.getElementById('total').textContent=adminAlerts.length;document.getElementById('active').textContent=adminAlerts.filter(a=>ACTIVE.includes(a.status)).length;document.getElementById('critical').textContent=adminAlerts.filter(a=>a.priority==='critical').length;document.getElementById('resolved').textContent=adminAlerts.filter(a=>a.status==='resolved').length;renderAdminMap();renderAdmin();
 }catch(e){document.getElementById('adminState').innerHTML='<div class="empty">'+esc(e.message)+'</div>'}
}

function renderAdminMap(){if(!window.L||!document.getElementById('adminMap'))return;const pts=adminAlerts.filter(a=>a.latitude!=null&&a.longitude!=null);if(!adminMap){adminMap=L.map('adminMap').setView(pts.length?[Number(pts[0].latitude),Number(pts[0].longitude)]:[20.5937,78.9629],pts.length?13:5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(adminMap);adminLayer=L.layerGroup().addTo(adminMap);heatLayer=L.layerGroup().addTo(adminMap)}adminLayer.clearLayers();heatLayer.clearLayers();pts.forEach(a=>{const lat=Number(a.latitude),lng=Number(a.longitude);L.marker([lat,lng]).bindPopup(`<strong>#${esc(a.id)} ${esc(a.alert_type)}</strong><br>${esc(a.resident_name||'Resident')}<br>${esc(a.status)}<br><a href="/emergency-history/?alert=${a.id}">Open incident</a>`).addTo(adminLayer);L.circle([lat,lng],{radius:a.status==='resolved'?80:150,weight:1,fillOpacity:a.status==='resolved'?.10:.22}).addTo(heatLayer)});if(pts.length)adminMap.fitBounds(L.latLngBounds(pts.map(a=>[Number(a.latitude),Number(a.longitude)])),{padding:[25,25]})}
function renderAdmin(){const q=(document.getElementById('search')?.value||'').toLowerCase(),st=document.getElementById('filter')?.value||'all',a=adminAlerts.filter(x=>(st==='all'||x.status===st)&&(!q||JSON.stringify(x).toLowerCase().includes(q)));document.getElementById('adminState').innerHTML=a.length?a.map(x=>`<div class="list-item"><div class="row"><strong>#${x.id} ${esc(x.alert_type)}</strong><span><span class="badge ${x.status}">${x.status}</span> <span class="badge ${x.priority}">${x.priority}</span></span></div><div class="meta">${esc(x.resident_name||'Resident')} · ${fmt(x.created_at)}</div><p class="muted" style="margin-top:6px">${esc(x.message||'Emergency alert')}</p><div class="actions"><a class="btn btn-light" href="/emergency-history/?alert=${x.id}">Open incident</a><a class="btn btn-light" target="_blank" href="https://www.google.com/maps?q=${x.latitude},${x.longitude}">📍 GPS</a>${x.resident_phone?`<a class="btn btn-light" href="tel:${esc(x.resident_phone)}">📞 Call resident</a>`:''}${ACTIVE.includes(x.status)?`<button class="btn btn-success" onclick="setStatus(${x.id},'resolved')">Resolve</button><button class="btn btn-danger" onclick="setStatus(${x.id},'cancelled')">Cancel</button><button class="btn btn-light" onclick="escalate(${x.id})">Escalate</button>`:''}<button class="btn btn-light" onclick="openChat(${x.id})">💬 Incident Chat</button></div></div>`).join(''):'<div class="empty">No matching incidents.</div>'}

async function loadIntelligence(){
 if(!isManager())return;
 try{const d=await CC.json('/api/response/society-intelligence/');const s=d.summary||{};document.getElementById('insightStats').innerHTML=`<div><strong>${s.total_incidents||0}</strong><span>Total incidents</span></div><div><strong>${s.active_incidents||0}</strong><span>Active now</span></div><div><strong>${s.available_volunteers||0}</strong><span>Available</span></div><div><strong>${s.busy_volunteers||0}</strong><span>Busy</span></div><div class="warn"><strong>${s.overloaded_volunteers||0}</strong><span>Overloaded</span></div><div><strong>${s.avg_response_seconds!=null?Math.round(s.avg_response_seconds)+'s':'—'}</strong><span>Avg response</span></div>`;document.getElementById('typeInsights').innerHTML=(d.by_type||[]).map(x=>`<div class="insight-row"><span>${esc(x.alert_type||'Other')}</span><strong>${x.count}</strong></div>`).join('')||'<div class="empty">No incident data yet.</div>';document.getElementById('hotspotInsights').innerHTML=(d.hotspots||[]).map(x=>`<div class="insight-row"><span>📍 ${esc(x.block)}</span><strong>${x.count}</strong></div>`).join('')||'<div class="empty">No hotspots yet.</div>';document.getElementById('responderInsights').innerHTML=(d.responders||[]).map(x=>`<div class="responder-insight"><div><strong>${esc(x.name)}</strong><small>${esc(x.role)}${x.block?' · '+esc(x.block):''}</small></div><div class="score">⭐ ${x.reliability_score}/100</div><div class="load ${x.active_load>=2?'overloaded':x.active_load?'busy':'free'}">${x.active_load>=2?'🔴 Overloaded':x.active_load?'🟡 '+x.active_load+' active':'🟢 Ready'}</div></div>`).join('')||'<div class="empty">No responders yet.</div>';document.getElementById('ownershipList').innerHTML=(d.ownership||[]).map(x=>`<div class="ownership-row"><div><strong>#${x.alert_id} · ${esc(x.type)}</strong><small>${esc(x.status)}</small></div><div>${x.owner?`<strong>👤 ${esc(x.owner)}</strong><small>${esc(x.owner_status)}</small>`:'<span class="unassigned">Unassigned — needs response</span>'}</div><a class="btn btn-light" href="/emergency-history/?alert=${x.alert_id}">Open</a></div>`).join('')||'<div class="empty">No active ownership records.</div>'}catch(e){['insightStats','typeInsights','hotspotInsights','responderInsights','ownershipList'].forEach(id=>{const el=document.getElementById(id);if(el)el.innerHTML='<div class="empty">'+esc(e.message)+'</div>'})}}
async function setStatus(id,status){try{await CC.json('/api/emergency-alerts/'+id+'/',{method:'PATCH',body:JSON.stringify({status})});toast('Incident updated','success');loadAdmin();loadIntelligence()}catch(e){toast(e.message,'error')}}
async function escalate(id){try{await CC.json('/api/response/alerts/'+id+'/escalate/',{method:'POST',body:'{}'});toast('Incident escalated','success');loadAdmin();loadIntelligence()}catch(e){toast(e.message,'error')}}
async function openChat(id){document.getElementById('chatModal').classList.add('show');document.getElementById('chatAlert').value=id;await loadChat(id)}
async function loadChat(id){try{const d=await CC.json('/api/response/alerts/'+id+'/chat/');const a=Array.isArray(d)?d:(d.results||[]);document.getElementById('chatMessages').innerHTML=a.length?a.map(m=>`<div class="list-item"><strong>${esc(m.sender_name||m.sender||'Responder')}</strong><p class="muted">${esc(m.message)}</p><div class="meta">${fmt(m.created_at)}</div></div>`).join(''):'<div class="empty chat-empty"><strong>💬 No updates yet</strong><p>Start the incident conversation. Your message will notify the response team.</p></div>'}catch(e){document.getElementById('chatMessages').innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}
async function sendChat(){const id=document.getElementById('chatAlert').value,msg=document.getElementById('chatText').value.trim();if(!msg)return;try{await CC.json('/api/response/alerts/'+id+'/chat/',{method:'POST',body:JSON.stringify({message:msg})});document.getElementById('chatText').value='';await loadChat(id)}catch(e){toast(e.message,'error')}}

document.addEventListener('DOMContentLoaded',()=>{if(!CC.requireLogin())return;applyAdminRoleCopy();loadAdmin();loadIntelligence();loadResponderDesk();setInterval(()=>{loadAdmin();loadIntelligence();loadResponderDesk()},8000);document.getElementById('sendChat')?.addEventListener('click',sendChat);document.getElementById('chatText')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendChat()}})});
