document.addEventListener('DOMContentLoaded',()=>{
 navUser(); setActiveNav(); applyRoleUI(); setupLanguageAndAssistant();
 document.querySelectorAll('[data-logout]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();CC.logout()}));
 const toggle=document.getElementById('menuToggle'),side=document.getElementById('sidebar'),overlay=document.getElementById('sidebarOverlay');
 const close=()=>{side?.classList.remove('open');overlay?.classList.remove('show')};
 toggle?.addEventListener('click',()=>{side?.classList.toggle('open');overlay?.classList.toggle('show')}); overlay?.addEventListener('click',close);
});
function applyRoleUI(){
 const u=CC.user||{}; const role=String(u.role||'').toLowerCase();
 const resident=role==='resident', command=['admin','superadmin','society_admin','security_admin','volunteer','security','security_volunteer'].includes(role), contact=['resident','guardian'].includes(role);
 document.querySelectorAll('[data-resident-only]').forEach(e=>e.style.display=resident?'flex':'none');
 document.querySelectorAll('[data-command-center]').forEach(e=>e.style.display=command?'flex':'none');
 document.querySelectorAll('[data-contact-role]').forEach(e=>e.style.display=contact?'flex':'none');
 const center=document.querySelector('[data-command-center] span:nth-child(2)');
 if(center){center.textContent=['volunteer','security','security_volunteer'].includes(role)?'Response Desk':role==='society_admin'?'Society Command':role==='superadmin'?'Platform Center':'Operations Center';}
}
function setActiveNav(){
 const path=location.pathname;
 document.querySelectorAll('[data-nav]').forEach(a=>{const k=a.dataset.nav;const m=(k==='dashboard'&&path==='/dashboard/')||(k==='sos'&&path.startsWith('/sos'))||(k==='location'&&path.startsWith('/location'))||(k==='contacts'&&path.startsWith('/emergency-contacts'))||(k==='history'&&path.startsWith('/emergency-history'))||(k==='notifications'&&path.startsWith('/notifications'))||(k==='admin'&&path.startsWith('/admin-portal'));a.classList.toggle('active',m)});
 const headings={dashboard:'Role dashboard',sos:'Emergency SOS',location:'Live GPS Tracking',contacts:'Emergency Contacts',history:'Incident Monitoring',notifications:'Notifications',admin:'Admin Response Center'};
 const active=document.querySelector('[data-nav].active');const h=document.getElementById('pageHeading');if(active&&h)h.textContent=headings[active.dataset.nav]||'Community safety';
}

const I18N={
 en:{'WORKSPACE':'WORKSPACE','Dashboard':'Dashboard','Live GPS':'Live GPS','Emergency Contacts':'Emergency Contacts','Incidents':'Incidents','Notifications':'Notifications','Response Center':'Response Center','Sign out':'Sign out','CARECONNECT':'CARECONNECT','Community safety':'Community safety','CareConnect Assistant':'CareConnect Assistant','Hi! I can guide you during an emergency.':'Hi! I can guide you during an emergency.','Emergency':'Emergency','Medical':'Medical','Security':'Security','Send':'Send','Ask CareConnect…':'Ask CareConnect…','Role dashboard':'Role dashboard','Emergency SOS':'Emergency SOS','Live GPS Tracking':'Live GPS Tracking','Incident Monitoring':'Incident Monitoring','Admin Response Center':'Admin Response Center','Welcome back':'Welcome back','Your emergency response workspace.':'Your emergency response workspace.','EMERGENCY ACCESS':'EMERGENCY ACCESS','Need help right now?':'Need help right now?','One tap sends your SOS, GPS location and alerts to your emergency response network.':'One tap sends your SOS, GPS location and alerts to your emergency response network.','Ready — no emergency is active.':'Ready — no emergency is active.','SOS':'SOS','ONE TAP':'ONE TAP','Cancel SOS':'Cancel SOS','YOUR WORKSPACE':'YOUR WORKSPACE','Emergency overview':'Emergency overview','System online':'System online','LIVE QUEUE':'LIVE QUEUE','Recent incidents':'Recent incidents','View all →':'View all →','RESPONSE FLOW':'RESPONSE FLOW','From SOS to resolution':'From SOS to resolution','Alert created':'Alert created','Responders notified':'Responders notified','Accepted / on the way':'Accepted / on the way','Arrived and resolved':'Arrived and resolved','Total incidents':'Total incidents','Active incidents':'Active incidents','Critical alerts':'Critical alerts','Resolved':'Resolved'},
 ta:{'WORKSPACE':'பணியிடம்','Dashboard':'டாஷ்போர்டு','Live GPS':'நேரடி GPS','Emergency Contacts':'அவசர தொடர்புகள்','Incidents':'சம்பவங்கள்','Notifications':'அறிவிப்புகள்','Response Center':'பதில் மையம்','Sign out':'வெளியேறு','CARECONNECT':'CARECONNECT','Community safety':'சமூக பாதுகாப்பு','CareConnect Assistant':'CareConnect உதவியாளர்','Hi! I can guide you during an emergency.':'வணக்கம்! அவசரநிலையில் உங்களுக்கு வழிகாட்ட முடியும்.','Emergency':'அவசரம்','Medical':'மருத்துவம்','Security':'பாதுகாப்பு','Send':'அனுப்பு','Ask CareConnect…':'CareConnect-ஐ கேளுங்கள்…','Role dashboard':'பங்கு டாஷ்போர்டு','Emergency SOS':'அவசர SOS','Live GPS Tracking':'நேரடி GPS கண்காணிப்பு','Incident Monitoring':'சம்பவ கண்காணிப்பு','Admin Response Center':'நிர்வாக பதில் மையம்','Welcome back':'மீண்டும் வரவேற்கிறோம்','Your emergency response workspace.':'உங்கள் அவசர பதில் பணியிடம்.','EMERGENCY ACCESS':'அவசர அணுகல்','Need help right now?':'இப்போது உதவி தேவையா?','One tap sends your SOS, GPS location and alerts to your emergency response network.':'ஒரு தொடுதலில் SOS, GPS இருப்பிடம் மற்றும் எச்சரிக்கை உங்கள் அவசர குழுவுக்கு அனுப்பப்படும்.','Ready — no emergency is active.':'தயார் — அவசரம் எதுவும் செயல்பாட்டில் இல்லை.','SOS':'SOS','ONE TAP':'ஒரே தொடுதல்','Cancel SOS':'SOS ரத்து','YOUR WORKSPACE':'உங்கள் பணியிடம்','Emergency overview':'அவசர நிலை சுருக்கம்','System online':'அமைப்பு ஆன்லைனில்','LIVE QUEUE':'நேரடி வரிசை','Recent incidents':'சமீபத்திய சம்பவங்கள்','View all →':'அனைத்தையும் காண்க →','RESPONSE FLOW':'பதில் நடைமுறை','From SOS to resolution':'SOS முதல் தீர்வு வரை','Alert created':'எச்சரிக்கை உருவாக்கப்பட்டது','Responders notified':'பதிலளிப்பவர்களுக்கு அறிவிக்கப்பட்டது','Accepted / on the way':'ஏற்றுக்கொள்ளப்பட்டது / வழியில்','Arrived and resolved':'வந்து தீர்க்கப்பட்டது','Total incidents':'மொத்த சம்பவங்கள்','Active incidents':'செயலில் உள்ள சம்பவங்கள்','Critical alerts':'முக்கிய எச்சரிக்கைகள்','Resolved':'தீர்க்கப்பட்டது'},
 hi:{'WORKSPACE':'कार्यस्थल','Dashboard':'डैशबोर्ड','Live GPS':'लाइव GPS','Emergency Contacts':'आपातकालीन संपर्क','Incidents':'घटनाएँ','Notifications':'सूचनाएँ','Response Center':'प्रतिक्रिया केंद्र','Sign out':'साइन आउट','CARECONNECT':'CARECONNECT','Community safety':'सामुदायिक सुरक्षा','CareConnect Assistant':'CareConnect सहायक','Hi! I can guide you during an emergency.':'नमस्ते! मैं आपात स्थिति में आपका मार्गदर्शन कर सकता हूँ।','Emergency':'आपातकाल','Medical':'चिकित्सा','Security':'सुरक्षा','Send':'भेजें','Ask CareConnect…':'CareConnect से पूछें…','Role dashboard':'भूमिका डैशबोर्ड','Emergency SOS':'आपातकालीन SOS','Live GPS Tracking':'लाइव GPS ट्रैकिंग','Incident Monitoring':'घटना निगरानी','Admin Response Center':'प्रशासन प्रतिक्रिया केंद्र','Welcome back':'वापसी पर स्वागत है','Your emergency response workspace.':'आपका आपातकालीन प्रतिक्रिया कार्यक्षेत्र।','EMERGENCY ACCESS':'आपातकालीन पहुँच','Need help right now?':'अभी मदद चाहिए?','One tap sends your SOS, GPS location and alerts to your emergency response network.':'एक टैप से SOS, GPS स्थान और अलर्ट आपकी आपातकालीन प्रतिक्रिया टीम को भेजे जाते हैं।','Ready — no emergency is active.':'तैयार — कोई आपातकाल सक्रिय नहीं है।','SOS':'SOS','ONE TAP':'एक टैप','Cancel SOS':'SOS रद्द करें','YOUR WORKSPACE':'आपका कार्यक्षेत्र','Emergency overview':'आपातकालीन अवलोकन','System online':'सिस्टम ऑनलाइन','LIVE QUEUE':'लाइव कतार','Recent incidents':'हाल की घटनाएँ','View all →':'सभी देखें →','RESPONSE FLOW':'प्रतिक्रिया प्रक्रिया','From SOS to resolution':'SOS से समाधान तक','Alert created':'अलर्ट बनाया गया','Responders notified':'प्रतिक्रिया दल को सूचित किया गया','Accepted / on the way':'स्वीकार / रास्ते में','Arrived and resolved':'पहुंचकर समाधान किया गया','Total incidents':'कुल घटनाएँ','Active incidents':'सक्रिय घटनाएँ','Critical alerts':'महत्वपूर्ण अलर्ट','Resolved':'समाधान किया गया'},
 te:{'WORKSPACE':'పని స్థలం','Dashboard':'డ్యాష్‌బోర్డ్','Live GPS':'లైవ్ GPS','Emergency Contacts':'అత్యవసర సంప్రదింపులు','Incidents':'సంఘటనలు','Notifications':'నోటిఫికేషన్లు','Response Center':'ప్రతిస్పందన కేంద్రం','Sign out':'సైన్ అవుట్','Community safety':'సామాజిక భద్రత','CareConnect Assistant':'CareConnect సహాయకుడు','Hi! I can guide you during an emergency.':'నమస్కారం! అత్యవసర సమయంలో నేను మీకు మార్గనిర్దేశం చేస్తాను.','Emergency':'అత్యవసరం','Medical':'వైద్యం','Security':'భద్రత','Send':'పంపండి','Ask CareConnect…':'CareConnect ను అడగండి…','Role dashboard':'పాత్ర డ్యాష్‌బోర్డ్','Emergency SOS':'అత్యవసర SOS','Live GPS Tracking':'లైవ్ GPS ట్రాకింగ్','Incident Monitoring':'సంఘటన పర్యవేక్షణ','Admin Response Center':'అడ్మిన్ ప్రతిస్పందన కేంద్రం','Welcome back':'తిరిగి స్వాగతం','Your emergency response workspace.':'మీ అత్యవసర ప్రతిస్పందన పని స్థలం.','EMERGENCY ACCESS':'అత్యవసర ప్రాప్యత','Need help right now?':'ఇప్పుడే సహాయం కావాలా?','One tap sends your SOS, GPS location and alerts to your emergency response network.':'ఒక్కసారి నొక్కితే SOS, GPS స్థానం మరియు హెచ్చరికలు మీ అత్యవసర ప్రతిస్పందన బృందానికి పంపబడతాయి.','Ready — no emergency is active.':'సిద్ధంగా ఉంది — అత్యవసరం ఏదీ సక్రియంగా లేదు.','SOS':'SOS','ONE TAP':'ఒక్క ట్యాప్','Cancel SOS':'SOS రద్దు','YOUR WORKSPACE':'మీ పని స్థలం','Emergency overview':'అత్యవసర అవలోకనం','System online':'సిస్టమ్ ఆన్‌లైన్','LIVE QUEUE':'లైవ్ క్యూ','Recent incidents':'ఇటీవలి సంఘటనలు','View all →':'అన్నీ చూడండి →','RESPONSE FLOW':'ప్రతిస్పందన విధానం','From SOS to resolution':'SOS నుండి పరిష్కారం వరకు','Alert created':'హెచ్చరిక సృష్టించబడింది','Responders notified':'ప్రతిస్పందనదారులకు తెలియజేయబడింది','Accepted / on the way':'ఆమోదించబడింది / మార్గంలో','Arrived and resolved':'చేరుకుని పరిష్కరించబడింది','Total incidents':'మొత్తం సంఘటనలు','Active incidents':'సక్రియ సంఘటనలు','Critical alerts':'క్రిటికల్ హెచ్చరికలు','Resolved':'పరిష్కరించబడింది'},
 kn:{'WORKSPACE':'ಕೆಲಸದ ಸ್ಥಳ','Dashboard':'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್','Live GPS':'ಲೈವ್ GPS','Emergency Contacts':'ತುರ್ತು ಸಂಪರ್ಕಗಳು','Incidents':'ಘಟನೆಗಳು','Notifications':'ಅಧಿಸೂಚನೆಗಳು','Response Center':'ಪ್ರತಿಕ್ರಿಯಾ ಕೇಂದ್ರ','Sign out':'ಸೈನ್ ಔಟ್','Community safety':'ಸಮುದಾಯ ಸುರಕ್ಷತೆ','CareConnect Assistant':'CareConnect ಸಹಾಯಕ','Hi! I can guide you during an emergency.':'ನಮಸ್ಕಾರ! ತುರ್ತು ಪರಿಸ್ಥಿತಿಯಲ್ಲಿ ನಾನು ನಿಮಗೆ ಮಾರ್ಗದರ್ಶನ ನೀಡುತ್ತೇನೆ.','Emergency':'ತುರ್ತು ಪರಿಸ್ಥಿತಿ','Medical':'ವೈದ್ಯಕೀಯ','Security':'ಭದ್ರತೆ','Send':'ಕಳುಹಿಸಿ','Ask CareConnect…':'CareConnect ಅನ್ನು ಕೇಳಿ…','Role dashboard':'ಪಾತ್ರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್','Emergency SOS':'ತುರ್ತು SOS','Live GPS Tracking':'ಲೈವ್ GPS ಟ್ರ್ಯಾಕಿಂಗ್','Incident Monitoring':'ಘಟನೆ ಮೇಲ್ವಿಚಾರಣೆ','Admin Response Center':'ನಿರ್ವಾಹಕ ಪ್ರತಿಕ್ರಿಯಾ ಕೇಂದ್ರ','Welcome back':'ಮತ್ತೆ ಸ್ವಾಗತ','Your emergency response workspace.':'ನಿಮ್ಮ ತುರ್ತು ಪ್ರತಿಕ್ರಿಯಾ ಕಾರ್ಯಸ್ಥಳ.','EMERGENCY ACCESS':'ತುರ್ತು ಪ್ರವೇಶ','Need help right now?':'ಈಗಲೇ ಸಹಾಯ ಬೇಕೇ?','One tap sends your SOS, GPS location and alerts to your emergency response network.':'ಒಮ್ಮೆ ಒತ್ತಿದರೆ SOS, GPS ಸ್ಥಳ ಮತ್ತು ಎಚ್ಚರಿಕೆಗಳು ನಿಮ್ಮ ತುರ್ತು ಪ್ರತಿಕ್ರಿಯಾ ತಂಡಕ್ಕೆ ಕಳುಹಿಸಲಾಗುತ್ತದೆ.','Ready — no emergency is active.':'ಸಿದ್ಧ — ಯಾವುದೇ ತುರ್ತು ಪರಿಸ್ಥಿತಿ ಸಕ್ರಿಯವಾಗಿಲ್ಲ.','SOS':'SOS','ONE TAP':'ಒಂದು ಟ್ಯಾಪ್','Cancel SOS':'SOS ರದ್ದುಮಾಡಿ','YOUR WORKSPACE':'ನಿಮ್ಮ ಕಾರ್ಯಸ್ಥಳ','Emergency overview':'ತುರ್ತು ಅವಲೋಕನ','System online':'ಸಿಸ್ಟಮ್ ಆನ್‌ಲೈನ್','LIVE QUEUE':'ಲೈವ್ ಸರತಿ','Recent incidents':'ಇತ್ತೀಚಿನ ಘಟನೆಗಳು','View all →':'ಎಲ್ಲವನ್ನೂ ನೋಡಿ →','RESPONSE FLOW':'ಪ್ರತಿಕ್ರಿಯಾ ಕ್ರಮ','From SOS to resolution':'SOS ನಿಂದ ಪರಿಹಾರವರೆಗೆ','Alert created':'ಎಚ್ಚರಿಕೆ ರಚಿಸಲಾಗಿದೆ','Responders notified':'ಪ್ರತಿಕ್ರಿಯಿಸುವವರಿಗೆ ತಿಳಿಸಲಾಗಿದೆ','Accepted / on the way':'ಸ್ವೀಕರಿಸಲಾಗಿದೆ / ದಾರಿಯಲ್ಲಿ','Arrived and resolved':'ತಲುಪಿ ಪರಿಹರಿಸಲಾಗಿದೆ','Total incidents':'ಒಟ್ಟು ಘಟನೆಗಳು','Active incidents':'ಸಕ್ರಿಯ ಘಟನೆಗಳು','Critical alerts':'ತೀವ್ರ ಎಚ್ಚರಿಕೆಗಳು','Resolved':'ಪರಿಹರಿಸಲಾಗಿದೆ'},
 ml:{'WORKSPACE':'പ്രവർത്തന മേഖല','Dashboard':'ഡാഷ്ബോർഡ്','Live GPS':'ലൈവ് GPS','Emergency Contacts':'അടിയന്തര ബന്ധങ്ങൾ','Incidents':'സംഭവങ്ങൾ','Notifications':'അറിയിപ്പുകൾ','Response Center':'പ്രതികരണ കേന്ദ്രം','Sign out':'പുറത്തുകടക്കുക','Community safety':'സമൂഹ സുരക്ഷ','CareConnect Assistant':'CareConnect സഹായി','Hi! I can guide you during an emergency.':'നമസ്കാരം! അടിയന്തര സാഹചര്യത്തിൽ ഞാൻ നിങ്ങളെ നയിക്കാം.','Emergency':'അടിയന്തരം','Medical':'മെഡിക്കൽ','Security':'സുരക്ഷ','Send':'അയയ്ക്കുക','Ask CareConnect…':'CareConnect-നോട് ചോദിക്കുക…','Role dashboard':'റോൾ ഡാഷ്ബോർഡ്','Emergency SOS':'അടിയന്തര SOS','Live GPS Tracking':'ലൈവ് GPS ട്രാക്കിംഗ്','Incident Monitoring':'സംഭവ നിരീക്ഷണം','Admin Response Center':'അഡ്മിൻ പ്രതികരണ കേന്ദ്രം','Welcome back':'വീണ്ടും സ്വാഗതം','Your emergency response workspace.':'നിങ്ങളുടെ അടിയന്തര പ്രതികരണ പ്രവർത്തനമേഖല.','EMERGENCY ACCESS':'അടിയന്തര പ്രവേശനം','Need help right now?':'ഇപ്പോൾ സഹായം വേണമോ?','One tap sends your SOS, GPS location and alerts to your emergency response network.':'ഒറ്റ ടാപ്പിലൂടെ SOS, GPS ലൊക്കേഷൻ, അലർട്ടുകൾ എന്നിവ പ്രതികരണ സംഘത്തിന് അയയ്ക്കും.','Ready — no emergency is active.':'തയ്യാർ — അടിയന്തര സാഹചര്യം സജീവമല്ല.','SOS':'SOS','ONE TAP':'ഒറ്റ ടാപ്പ്','Cancel SOS':'SOS റദ്ദാക്കുക','YOUR WORKSPACE':'നിങ്ങളുടെ പ്രവർത്തനമേഖല','Emergency overview':'അടിയന്തര അവലോകനം','System online':'സിസ്റ്റം ഓൺലൈനിൽ','LIVE QUEUE':'ലൈവ് ക്യൂ','Recent incidents':'സമീപകാല സംഭവങ്ങൾ','View all →':'എല്ലാം കാണുക →','RESPONSE FLOW':'പ്രതികരണ ഘട്ടങ്ങൾ','From SOS to resolution':'SOS മുതൽ പരിഹാരം വരെ','Alert created':'അലർട്ട് സൃഷ്ടിച്ചു','Responders notified':'പ്രതികരണ സംഘത്തെ അറിയിച്ചു','Accepted / on the way':'സ്വീകരിച്ചു / വഴിയിൽ','Arrived and resolved':'എത്തി പരിഹരിച്ചു','Total incidents':'ആകെ സംഭവങ്ങൾ','Active incidents':'സജീവ സംഭവങ്ങൾ','Critical alerts':'ഗുരുതര അലർട്ടുകൾ','Resolved':'പരിഹരിച്ചു'},
 mr:{'WORKSPACE':'कार्यस्थळ','Dashboard':'डॅशबोर्ड','Live GPS':'लाईव्ह GPS','Emergency Contacts':'आपत्कालीन संपर्क','Incidents':'घटना','Notifications':'सूचना','Response Center':'प्रतिक्रिया केंद्र','Sign out':'साइन आउट','Community safety':'समुदाय सुरक्षा','CareConnect Assistant':'CareConnect सहाय्यक','Hi! I can guide you during an emergency.':'नमस्कार! आपत्कालीन परिस्थितीत मी तुम्हाला मार्गदर्शन करू शकतो.','Emergency':'आपत्काल','Medical':'वैद्यकीय','Security':'सुरक्षा','Send':'पाठवा','Ask CareConnect…':'CareConnect ला विचारा…','Role dashboard':'भूमिका डॅशबोर्ड','Emergency SOS':'आपत्कालीन SOS','Live GPS Tracking':'लाईव्ह GPS ट्रॅकिंग','Incident Monitoring':'घटना निरीक्षण','Admin Response Center':'प्रशासन प्रतिसाद केंद्र','Welcome back':'पुन्हा स्वागत','Your emergency response workspace.':'तुमचे आपत्कालीन प्रतिसाद कार्यक्षेत्र.','EMERGENCY ACCESS':'आपत्कालीन प्रवेश','Need help right now?':'आत्ता मदत हवी आहे का?','One tap sends your SOS, GPS location and alerts to your emergency response network.':'एका टॅपने SOS, GPS स्थान आणि अलर्ट तुमच्या आपत्कालीन प्रतिसाद पथकाला पाठवले जातील.','Ready — no emergency is active.':'तयार — कोणतीही आपत्कालीन स्थिती सक्रिय नाही.','SOS':'SOS','ONE TAP':'एक टॅप','Cancel SOS':'SOS रद्द करा','YOUR WORKSPACE':'तुमचे कार्यक्षेत्र','Emergency overview':'आपत्कालीन आढावा','System online':'सिस्टम ऑनलाइन','LIVE QUEUE':'लाईव्ह रांग','Recent incidents':'अलीकडील घटना','View all →':'सर्व पहा →','RESPONSE FLOW':'प्रतिसाद प्रक्रिया','From SOS to resolution':'SOS पासून निराकरणापर्यंत','Alert created':'अलर्ट तयार केला','Responders notified':'प्रतिसाद पथकाला कळवले','Accepted / on the way':'स्वीकारले / मार्गावर','Arrived and resolved':'पोहोचून निराकरण केले','Total incidents':'एकूण घटना','Active incidents':'सक्रिय घटना','Critical alerts':'गंभीर अलर्ट','Resolved':'निराकरण झाले'},
 bn:{'WORKSPACE':'কর্মক্ষেত্র','Dashboard':'ড্যাশবোর্ড','Live GPS':'লাইভ GPS','Emergency Contacts':'জরুরি যোগাযোগ','Incidents':'ঘটনা','Notifications':'বিজ্ঞপ্তি','Response Center':'প্রতিক্রিয়া কেন্দ্র','Sign out':'সাইন আউট','Community safety':'সম্প্রদায় নিরাপত্তা','CareConnect Assistant':'CareConnect সহায়ক','Hi! I can guide you during an emergency.':'নমস্কার! জরুরি অবস্থায় আমি আপনাকে নির্দেশনা দিতে পারি।','Emergency':'জরুরি','Medical':'চিকিৎসা','Security':'নিরাপত্তা','Send':'পাঠান','Ask CareConnect…':'CareConnect-কে জিজ্ঞাসা করুন…','Role dashboard':'ভূমিকা ড্যাশবোর্ড','Emergency SOS':'জরুরি SOS','Live GPS Tracking':'লাইভ GPS ট্র্যাকিং','Incident Monitoring':'ঘটনা পর্যবেক্ষণ','Admin Response Center':'অ্যাডমিন প্রতিক্রিয়া কেন্দ্র','Welcome back':'আবার স্বাগতম','Your emergency response workspace.':'আপনার জরুরি প্রতিক্রিয়া কর্মক্ষেত্র।','EMERGENCY ACCESS':'জরুরি প্রবেশ','Need help right now?':'এখনই সাহায্য দরকার?','One tap sends your SOS, GPS location and alerts to your emergency response network.':'এক ট্যাপে SOS, GPS অবস্থান এবং সতর্কতা আপনার জরুরি প্রতিক্রিয়া দলের কাছে পাঠানো হবে।','Ready — no emergency is active.':'প্রস্তুত — কোনো জরুরি অবস্থা সক্রিয় নেই।','SOS':'SOS','ONE TAP':'এক ট্যাপ','Cancel SOS':'SOS বাতিল','YOUR WORKSPACE':'আপনার কর্মক্ষেত্র','Emergency overview':'জরুরি সারাংশ','System online':'সিস্টেম অনলাইন','LIVE QUEUE':'লাইভ কিউ','Recent incidents':'সাম্প্রতিক ঘটনা','View all →':'সব দেখুন →','RESPONSE FLOW':'প্রতিক্রিয়া ধাপ','From SOS to resolution':'SOS থেকে সমাধান পর্যন্ত','Alert created':'সতর্কতা তৈরি হয়েছে','Responders notified':'প্রতিক্রিয়াকারীদের জানানো হয়েছে','Accepted / on the way':'গ্রহণ করা হয়েছে / পথে','Arrived and resolved':'পৌঁছে সমাধান করা হয়েছে','Total incidents':'মোট ঘটনা','Active incidents':'সক্রিয় ঘটনা','Critical alerts':'গুরুতর সতর্কতা','Resolved':'সমাধান হয়েছে'},
 gu:{'WORKSPACE':'કાર્યસ્થળ','Dashboard':'ડેશબોર્ડ','Live GPS':'લાઇવ GPS','Emergency Contacts':'કટોકટી સંપર્કો','Incidents':'ઘટનાઓ','Notifications':'સૂચનાઓ','Response Center':'પ્રતિસાદ કેન્દ્ર','Sign out':'સાઇન આઉટ','Community safety':'સમુદાય સુરક્ષા','CareConnect Assistant':'CareConnect સહાયક','Hi! I can guide you during an emergency.':'નમસ્તે! કટોકટીમાં હું તમને માર્ગદર્શન આપી શકું છું.','Emergency':'કટોકટી','Medical':'તબીબી','Security':'સુરક્ષા','Send':'મોકલો','Ask CareConnect…':'CareConnect ને પૂછો…','Role dashboard':'ભૂમિકા ડેશબોર્ડ','Emergency SOS':'કટોકટી SOS','Live GPS Tracking':'લાઇવ GPS ટ્રેકિંગ','Incident Monitoring':'ઘટના દેખરેખ','Admin Response Center':'એડમિન પ્રતિસાદ કેન્દ્ર','Welcome back':'ફરી સ્વાગત છે','Your emergency response workspace.':'તમારું કટોકટી પ્રતિસાદ કાર્યસ્થળ.','EMERGENCY ACCESS':'કટોકટી ઍક્સેસ','Need help right now?':'હમણાં મદદ જોઈએ?','One tap sends your SOS, GPS location and alerts to your emergency response network.':'એક ટૅપથી SOS, GPS સ્થાન અને ચેતવણીઓ તમારા કટોકટી પ્રતિસાદ નેટવર્કને મોકલાશે.','Ready — no emergency is active.':'તૈયાર — કોઈ કટોકટી સક્રિય નથી.','SOS':'SOS','ONE TAP':'એક ટૅપ','Cancel SOS':'SOS રદ કરો','YOUR WORKSPACE':'તમારું કાર્યસ્થળ','Emergency overview':'કટોકટી ઝાંખી','System online':'સિસ્ટમ ઓનલાઇન','LIVE QUEUE':'લાઇવ કતાર','Recent incidents':'તાજેતરની ઘટનાઓ','View all →':'બધું જુઓ →','RESPONSE FLOW':'પ્રતિસાદ પ્રવાહ','From SOS to resolution':'SOS થી ઉકેલ સુધી','Alert created':'ચેતવણી બનાવાઈ','Responders notified':'પ્રતિસાદકર્તાઓને જાણ કરાઈ','Accepted / on the way':'સ્વીકાર્યું / માર્ગમાં','Arrived and resolved':'પહોંચી ઉકેલ્યું','Total incidents':'કુલ ઘટનાઓ','Active incidents':'સક્રિય ઘટનાઓ','Critical alerts':'ગંભીર ચેતવણીઓ','Resolved':'ઉકેલાયું'},
 pa:{'WORKSPACE':'ਕਾਰਜਸਥਾਨ','Dashboard':'ਡੈਸ਼ਬੋਰਡ','Live GPS':'ਲਾਈਵ GPS','Emergency Contacts':'ਐਮਰਜੈਂਸੀ ਸੰਪਰਕ','Incidents':'ਘਟਨਾਵਾਂ','Notifications':'ਸੂਚਨਾਵਾਂ','Response Center':'ਜਵਾਬ ਕੇਂਦਰ','Sign out':'ਸਾਈਨ ਆਉਟ','Community safety':'ਕਮਿਊਨਿਟੀ ਸੁਰੱਖਿਆ','CareConnect Assistant':'CareConnect ਸਹਾਇਕ','Hi! I can guide you during an emergency.':'ਸਤ ਸ੍ਰੀ ਅਕਾਲ! ਐਮਰਜੈਂਸੀ ਵਿੱਚ ਮੈਂ ਤੁਹਾਡੀ ਮਦਦ ਕਰ ਸਕਦਾ ਹਾਂ।','Emergency':'ਐਮਰਜੈਂਸੀ','Medical':'ਮੈਡੀਕਲ','Security':'ਸੁਰੱਖਿਆ','Send':'ਭੇਜੋ','Ask CareConnect…':'CareConnect ਨੂੰ ਪੁੱਛੋ…','Role dashboard':'ਭੂਮਿਕਾ ਡੈਸ਼ਬੋਰਡ','Emergency SOS':'ਐਮਰਜੈਂਸੀ SOS','Live GPS Tracking':'ਲਾਈਵ GPS ਟ੍ਰੈਕਿੰਗ','Incident Monitoring':'ਘਟਨਾ ਨਿਗਰਾਨੀ','Admin Response Center':'ਐਡਮਿਨ ਜਵਾਬ ਕੇਂਦਰ','Welcome back':'ਵਾਪਸੀ ਤੇ ਸਵਾਗਤ','Your emergency response workspace.':'ਤੁਹਾਡਾ ਐਮਰਜੈਂਸੀ ਜਵਾਬ ਕਾਰਜਸਥਾਨ।','EMERGENCY ACCESS':'ਐਮਰਜੈਂਸੀ ਪਹੁੰਚ','Need help right now?':'ਹੁਣੇ ਮਦਦ ਚਾਹੀਦੀ ਹੈ?','One tap sends your SOS, GPS location and alerts to your emergency response network.':'ਇੱਕ ਟੈਪ ਨਾਲ SOS, GPS ਸਥਾਨ ਅਤੇ ਚੇਤਾਵਨੀਆਂ ਤੁਹਾਡੀ ਐਮਰਜੈਂਸੀ ਟੀਮ ਨੂੰ ਭੇਜੀਆਂ ਜਾਣਗੀਆਂ।','Ready — no emergency is active.':'ਤਿਆਰ — ਕੋਈ ਐਮਰਜੈਂਸੀ ਸਰਗਰਮ ਨਹੀਂ ਹੈ।','SOS':'SOS','ONE TAP':'ਇੱਕ ਟੈਪ','Cancel SOS':'SOS ਰੱਦ ਕਰੋ','YOUR WORKSPACE':'ਤੁਹਾਡਾ ਕਾਰਜਸਥਾਨ','Emergency overview':'ਐਮਰਜੈਂਸੀ ਝਲਕ','System online':'ਸਿਸਟਮ ਆਨਲਾਈਨ','LIVE QUEUE':'ਲਾਈਵ ਕਤਾਰ','Recent incidents':'ਹਾਲੀਆ ਘਟਨਾਵਾਂ','View all →':'ਸਭ ਵੇਖੋ →','RESPONSE FLOW':'ਜਵਾਬ ਪ੍ਰਕਿਰਿਆ','From SOS to resolution':'SOS ਤੋਂ ਹੱਲ ਤੱਕ','Alert created':'ਅਲਰਟ ਬਣਾਇਆ ਗਿਆ','Responders notified':'ਜਵਾਬ ਦੇਣ ਵਾਲਿਆਂ ਨੂੰ ਸੂਚਿਤ ਕੀਤਾ ਗਿਆ','Accepted / on the way':'ਸਵੀਕਾਰ / ਰਸਤੇ ਵਿੱਚ','Arrived and resolved':'ਪਹੁੰਚ ਕੇ ਹੱਲ ਕੀਤਾ','Total incidents':'ਕੁੱਲ ਘਟਨਾਵਾਂ','Active incidents':'ਸਰਗਰਮ ਘਟਨਾਵਾਂ','Critical alerts':'ਗੰਭੀਰ ਅਲਰਟ','Resolved':'ਹੱਲ ਕੀਤਾ ਗਿਆ'},
 or:{'WORKSPACE':'କାର୍ଯ୍ୟସ୍ଥଳ','Dashboard':'ଡ୍ୟାସବୋର୍ଡ','Live GPS':'ଲାଇଭ GPS','Emergency Contacts':'ଜରୁରୀ ସମ୍ପର୍କ','Incidents':'ଘଟଣା','Notifications':'ବିଜ୍ଞପ୍ତି','Response Center':'ପ୍ରତିକ୍ରିୟା କେନ୍ଦ୍ର','Sign out':'ସାଇନ୍ ଆଉଟ୍','Community safety':'ସମୁଦାୟ ସୁରକ୍ଷା','CareConnect Assistant':'CareConnect ସହାୟକ','Hi! I can guide you during an emergency.':'ନମସ୍କାର! ଜରୁରୀ ସମୟରେ ମୁଁ ଆପଣଙ୍କୁ ମାର୍ଗଦର୍ଶନ କରିପାରିବି।','Emergency':'ଜରୁରୀକାଳୀନ','Medical':'ଚିକିତ୍ସା','Security':'ସୁରକ୍ଷା','Send':'ପଠାନ୍ତୁ','Ask CareConnect…':'CareConnect କୁ ପଚାରନ୍ତୁ…','Role dashboard':'ଭୂମିକା ଡ୍ୟାସବୋର୍ଡ','Emergency SOS':'ଜରୁରୀ SOS','Live GPS Tracking':'ଲାଇଭ GPS ଟ୍ରାକିଂ','Incident Monitoring':'ଘଟଣା ନିରୀକ୍ଷଣ','Admin Response Center':'ଆଡମିନ୍ ପ୍ରତିକ୍ରିୟା କେନ୍ଦ୍ର','Welcome back':'ପୁଣି ସ୍ୱାଗତ','Your emergency response workspace.':'ଆପଣଙ୍କ ଜରୁରୀ ପ୍ରତିକ୍ରିୟା କାର୍ଯ୍ୟସ୍ଥଳ।','EMERGENCY ACCESS':'ଜରୁରୀ ପ୍ରବେଶ','Need help right now?':'ଏବେ ସାହାଯ୍ୟ ଦରକାର କି?','One tap sends your SOS, GPS location and alerts to your emergency response network.':'ଗୋଟିଏ ଟ୍ୟାପ୍‌ରେ SOS, GPS ଅବସ୍ଥାନ ଏବଂ ସତର୍କତା ଆପଣଙ୍କ ଜରୁରୀ ପ୍ରତିକ୍ରିୟା ଦଳକୁ ପଠାଯିବ।','Ready — no emergency is active.':'ପ୍ରସ୍ତୁତ — କୌଣସି ଜରୁରୀକାଳୀନ ସ୍ଥିତି ସକ୍ରିୟ ନୁହେଁ।','SOS':'SOS','ONE TAP':'ଗୋଟିଏ ଟ୍ୟାପ୍','Cancel SOS':'SOS ବାତିଲ୍','YOUR WORKSPACE':'ଆପଣଙ୍କ କାର୍ଯ୍ୟସ୍ଥଳ','Emergency overview':'ଜରୁରୀ ଅବଲୋକନ','System online':'ସିଷ୍ଟମ୍ ଅନଲାଇନ୍','LIVE QUEUE':'ଲାଇଭ୍ ଧାଡି','Recent incidents':'ସମ୍ପ୍ରତି ଘଟଣା','View all →':'ସବୁ ଦେଖନ୍ତୁ →','RESPONSE FLOW':'ପ୍ରତିକ୍ରିୟା ପ୍ରବାହ','From SOS to resolution':'SOS ରୁ ସମାଧାନ ପର୍ଯ୍ୟନ୍ତ','Alert created':'ସତର୍କତା ସୃଷ୍ଟି ହେଲା','Responders notified':'ପ୍ରତିକ୍ରିୟାଦାତାଙ୍କୁ ସୂଚିତ କରାଗଲା','Accepted / on the way':'ଗ୍ରହଣ / ରାସ୍ତାରେ','Arrived and resolved':'ପହଞ୍ଚି ସମାଧାନ କରାଗଲା','Total incidents':'ମୋଟ ଘଟଣା','Active incidents':'ସକ୍ରିୟ ଘଟଣା','Critical alerts':'ଗୁରୁତର ସତର୍କତା','Resolved':'ସମାଧାନ ହେଲା'}
};

const AI_RESPONSES={
 en:{emergency:'If this is an emergency, press SOS. Your GPS will be captured and responders will be notified.',medical:'For a medical emergency, move to a safe place, call emergency services if needed, and use SOS.',security:'For immediate danger, press SOS so available responders and security can receive your location.',default:'I can help with SOS, medical emergencies, security, GPS, notifications and emergency contacts.'},
 ta:{emergency:'அவசரநிலை என்றால் SOS அழுத்துங்கள். உங்கள் GPS இருப்பிடம் பதிவு செய்யப்பட்டு பதிலளிப்பவர்களுக்கு அறிவிக்கப்படும்.',medical:'மருத்துவ அவசரநிலையில் பாதுகாப்பான இடத்திற்குச் சென்று தேவையானால் அவசர சேவையை அழைத்து SOS பயன்படுத்துங்கள்.',security:'உடனடி ஆபத்து என்றால் SOS அழுத்துங்கள். பதிலளிப்பவர்கள் மற்றும் பாதுகாப்புக் குழுவுக்கு உங்கள் இருப்பிடம் செல்லும்.',default:'SOS, மருத்துவ அவசரம், பாதுகாப்பு, GPS, அறிவிப்புகள் மற்றும் அவசர தொடர்புகள் குறித்து நான் உதவ முடியும்.'},
 hi:{emergency:'आपात स्थिति में SOS दबाएँ। आपका GPS स्थान लिया जाएगा और प्रतिक्रिया दल को सूचित किया जाएगा।',medical:'चिकित्सीय आपात स्थिति में सुरक्षित स्थान पर जाएँ, जरूरत हो तो आपात सेवा को कॉल करें और SOS का उपयोग करें।',security:'तत्काल खतरे में SOS दबाएँ ताकि उपलब्ध प्रतिक्रिया दल और सुरक्षा को आपका स्थान मिल सके।',default:'मैं SOS, चिकित्सा आपातकाल, सुरक्षा, GPS, सूचनाओं और आपातकालीन संपर्कों में मदद कर सकता हूँ.'},
 te:{emergency:'అత్యవసర పరిస్థితిలో SOS నొక్కండి. మీ GPS స్థానం తీసుకుని ప్రతిస్పందన బృందానికి తెలియజేస్తాం.',medical:'వైద్య అత్యవసర పరిస్థితిలో సురక్షిత ప్రదేశానికి వెళ్లి అవసరమైతే అత్యవసర సేవలను కాల్ చేసి SOS ఉపయోగించండి.',security:'తక్షణ ప్రమాదంలో SOS నొక్కండి. అందుబాటులో ఉన్న భద్రతా బృందానికి మీ స్థానం చేరుతుంది.',default:'SOS, వైద్య అత్యవసరాలు, భద్రత, GPS, నోటిఫికేషన్లు మరియు అత్యవసర సంప్రదింపులలో నేను సహాయం చేయగలను.'},
 kn:{emergency:'ತುರ್ತು ಪರಿಸ್ಥಿತಿಯಲ್ಲಿ SOS ಒತ್ತಿರಿ. ನಿಮ್ಮ GPS ಸ್ಥಳವನ್ನು ಪಡೆದು ಪ್ರತಿಕ್ರಿಯಾ ತಂಡಕ್ಕೆ ತಿಳಿಸಲಾಗುತ್ತದೆ.',medical:'ವೈದ್ಯಕೀಯ ತುರ್ತು ಪರಿಸ್ಥಿತಿಯಲ್ಲಿ ಸುರಕ್ಷಿತ ಸ್ಥಳಕ್ಕೆ ಹೋಗಿ, ಅಗತ್ಯವಿದ್ದರೆ ತುರ್ತು ಸೇವೆಗೆ ಕರೆ ಮಾಡಿ ಮತ್ತು SOS ಬಳಸಿ.',security:'ತಕ್ಷಣದ ಅಪಾಯವಿದ್ದರೆ SOS ಒತ್ತಿರಿ. ಲಭ್ಯವಿರುವ ಭದ್ರತಾ ಮತ್ತು ಪ್ರತಿಕ್ರಿಯಾ ತಂಡಕ್ಕೆ ನಿಮ್ಮ ಸ್ಥಳ ತಲುಪುತ್ತದೆ.',default:'SOS, ವೈದ್ಯಕೀಯ ತುರ್ತು ಪರಿಸ್ಥಿತಿ, ಭದ್ರತೆ, GPS, ಅಧಿಸೂಚನೆಗಳು ಮತ್ತು ತುರ್ತು ಸಂಪರ್ಕಗಳಲ್ಲಿ ನಾನು ಸಹಾಯ ಮಾಡಬಹುದು.'},
 ml:{emergency:'അടിയന്തര സാഹചര്യമാണെങ്കിൽ SOS അമർത്തുക. നിങ്ങളുടെ GPS ലൊക്കേഷൻ എടുത്ത് പ്രതികരണ സംഘത്തെ അറിയിക്കും.',medical:'മെഡിക്കൽ അടിയന്തരാവസ്ഥയിൽ സുരക്ഷിതമായ സ്ഥലത്തേക്ക് മാറി ആവശ്യമായാൽ അടിയന്തര സേവനത്തെ വിളിച്ച് SOS ഉപയോഗിക്കുക.',security:'ഉടൻ അപകടമുണ്ടെങ്കിൽ SOS അമർത്തുക. ലഭ്യമായ സുരക്ഷാ സംഘത്തിനും പ്രതികരണ സംഘത്തിനും നിങ്ങളുടെ ലൊക്കേഷൻ ലഭിക്കും.',default:'SOS, മെഡിക്കൽ അടിയന്തരാവസ്ഥ, സുരക്ഷ, GPS, അറിയിപ്പുകൾ, അടിയന്തര ബന്ധങ്ങൾ എന്നിവയിൽ ഞാൻ സഹായിക്കും.'},
 mr:{emergency:'आपत्कालीन परिस्थितीत SOS दाबा. तुमचे GPS स्थान घेतले जाईल आणि प्रतिसाद पथकाला कळवले जाईल.',medical:'वैद्यकीय आपत्कालात सुरक्षित ठिकाणी जा, गरज असल्यास आपत्कालीन सेवेला कॉल करा आणि SOS वापरा.',security:'तात्काळ धोका असल्यास SOS दाबा. उपलब्ध सुरक्षा आणि प्रतिसाद पथकाला तुमचे स्थान मिळेल.',default:'मी SOS, वैद्यकीय आपत्काल, सुरक्षा, GPS, सूचना आणि आपत्कालीन संपर्कांमध्ये मदत करू शकतो.'},
 bn:{emergency:'জরুরি অবস্থায় SOS চাপুন। আপনার GPS অবস্থান নেওয়া হবে এবং প্রতিক্রিয়া দলকে জানানো হবে।',medical:'চিকিৎসা জরুরি অবস্থায় নিরাপদ স্থানে যান, প্রয়োজনে জরুরি পরিষেবায় কল করুন এবং SOS ব্যবহার করুন।',security:'তাৎক্ষণিক বিপদে SOS চাপুন যাতে নিরাপত্তা ও প্রতিক্রিয়া দল আপনার অবস্থান পায়।',default:'আমি SOS, চিকিৎসা জরুরি অবস্থা, নিরাপত্তা, GPS, বিজ্ঞপ্তি এবং জরুরি যোগাযোগে সাহায্য করতে পারি।'},
 gu:{emergency:'કટોકટીમાં SOS દબાવો. તમારું GPS સ્થાન લેવામાં આવશે અને પ્રતિસાદ ટીમને જાણ થશે.',medical:'તબીબી કટોકટીમાં સુરક્ષિત સ્થળે જાઓ, જરૂર હોય તો કટોકટી સેવા બોલાવો અને SOS વાપરો.',security:'તાત્કાલિક જોખમમાં SOS દબાવો જેથી સુરક્ષા અને પ્રતિસાદ ટીમને તમારું સ્થાન મળે.',default:'હું SOS, તબીબી કટોકટી, સુરક્ષા, GPS, સૂચનાઓ અને કટોકટી સંપર્કોમાં મદદ કરી શકું છું.'},
 pa:{emergency:'ਐਮਰਜੈਂਸੀ ਵਿੱਚ SOS ਦਬਾਓ। ਤੁਹਾਡਾ GPS ਸਥਾਨ ਲਿਆ ਜਾਵੇਗਾ ਅਤੇ ਜਵਾਬ ਟੀਮ ਨੂੰ ਸੂਚਿਤ ਕੀਤਾ ਜਾਵੇਗਾ।',medical:'ਮੈਡੀਕਲ ਐਮਰਜੈਂਸੀ ਵਿੱਚ ਸੁਰੱਖਿਅਤ ਥਾਂ ਤੇ ਜਾਓ, ਲੋੜ ਹੋਵੇ ਤਾਂ ਐਮਰਜੈਂਸੀ ਸੇਵਾ ਨੂੰ ਕਾਲ ਕਰੋ ਅਤੇ SOS ਵਰਤੋ।',security:'ਤੁਰੰਤ ਖਤਰੇ ਵਿੱਚ SOS ਦਬਾਓ ਤਾਂ ਜੋ ਸੁਰੱਖਿਆ ਅਤੇ ਜਵਾਬ ਟੀਮ ਨੂੰ ਤੁਹਾਡਾ ਸਥਾਨ ਮਿਲ ਸਕੇ।',default:'ਮੈਂ SOS, ਮੈਡੀਕਲ ਐਮਰਜੈਂਸੀ, ਸੁਰੱਖਿਆ, GPS, ਸੂਚਨਾਵਾਂ ਅਤੇ ਐਮਰਜੈਂਸੀ ਸੰਪਰਕਾਂ ਵਿੱਚ ਮਦਦ ਕਰ ਸਕਦਾ ਹਾਂ।'},
 or:{emergency:'ଜରୁରୀ ସ୍ଥିତିରେ SOS ଦବାନ୍ତୁ। ଆପଣଙ୍କ GPS ଅବସ୍ଥାନ ନିଆଯାଇ ପ୍ରତିକ୍ରିୟା ଦଳକୁ ଜଣାଯିବ।',medical:'ଚିକିତ୍ସା ଜରୁରୀ ସ୍ଥିତିରେ ସୁରକ୍ଷିତ ସ୍ଥାନକୁ ଯାଆନ୍ତୁ, ଆବଶ୍ୟକ ହେଲେ ଜରୁରୀ ସେବାକୁ ଫୋନ୍ କରନ୍ତୁ ଏବଂ SOS ବ୍ୟବହାର କରନ୍ତୁ।',security:'ତୁରନ୍ତ ବିପଦରେ SOS ଦବାନ୍ତୁ, ଯାହାଦ୍ୱାରା ସୁରକ୍ଷା ଓ ପ୍ରତିକ୍ରିୟା ଦଳ ଆପଣଙ୍କ ଅବସ୍ଥାନ ପାଇପାରିବେ।',default:'SOS, ଚିକିତ୍ସା ଜରୁରୀ ସ୍ଥିତି, ସୁରକ୍ଷା, GPS, ବିଜ୍ଞପ୍ତି ଏବଂ ଜରୁରୀ ସମ୍ପର୍କରେ ମୁଁ ସାହାଯ୍ୟ କରିପାରିବି।'}
};
function currentLang(){return localStorage.getItem('careconnect_language')||'en'}
function setupLanguageAndAssistant(){}
function applyLanguage(lang){
 const dict=I18N[lang]||I18N.en;
 document.documentElement.lang=lang;
 document.querySelectorAll('body *').forEach(el=>{
   if(el.children.length===0 && el.textContent.trim()){const key=el.textContent.trim();if(dict[key])el.textContent=dict[key]}
   if(el.tagName==='INPUT' || el.tagName==='TEXTAREA'){const key=el.getAttribute('placeholder');if(key&&dict[key])el.setAttribute('placeholder',dict[key])}
 });
 const a=document.querySelector('.ai-head strong'),i=document.getElementById('aiInput');if(a)a.textContent=dict['CareConnect Assistant']||'CareConnect Assistant';if(i)i.placeholder=dict['Ask CareConnect…']||'Ask CareConnect…';
 const msg=document.querySelector('#aiMessages .bot');if(msg)msg.textContent=dict['Hi! I can guide you during an emergency.']||I18N.en['Hi! I can guide you during an emergency.'];
}

window.addEventListener('online',()=>{const b=document.getElementById('offlineBanner');if(b)b.hidden=true});
window.addEventListener('offline',()=>{const b=document.getElementById('offlineBanner');if(b)b.hidden=false});
