# Generated by Django 5.0.6 on 2026-08-26 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='locationhistory',
            new_name='tracking_lo_user_id_e660ce_idx',
            old_name='tracking_lo_user_id_5e1a3b_idx',
        ),
    ]
