# Generated by Django 5.0.6 on 2026-08-26 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety_companion', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='safetyroutesegment',
            new_name='safety_comp_society_a59411_idx',
            old_name='safety_comp_society_3f0a0b_idx',
        ),
        migrations.RenameIndex(
            model_name='safetyroutesegment',
            new_name='safety_comp_start_l_d88236_idx',
            old_name='safety_comp_start_l_4e1f4b_idx',
        ),
        migrations.RenameIndex(
            model_name='safetyroutesegment',
            new_name='safety_comp_end_lat_fe0077_idx',
            old_name='safety_comp_end_lat_0db6b1_idx',
        ),
        migrations.RenameIndex(
            model_name='safetysignal',
            new_name='safety_comp_user_id_6d5f87_idx',
            old_name='safety_comp_user_id_6a2c0c_idx',
        ),
        migrations.RenameIndex(
            model_name='wellnesscheckin',
            new_name='safety_comp_status_1e72cd_idx',
            old_name='safety_comp_status_0aee4b_idx',
        ),
        migrations.RenameIndex(
            model_name='wellnesscheckin',
            new_name='safety_comp_status_2ade26_idx',
            old_name='safety_comp_status_8f77b6_idx',
        ),
    ]
